import prisma from "../../src/config/db";
import { register } from "../../src/modules/auth/auth.service";
import {
  createSellerProfile,
  getMySellerProfile,
  updateSellerProfile,
  getPublicSellerProfile,
} from "../../src/modules/seller/seller.service";

// ─── mock R2 uploads ──────────────────────────────────────────────────────────
jest.mock("../../src/utils/upload", () => ({
  upload: { single: () => (_req: any, _res: any, next: any) => next() },
  uploadToR2: jest.fn().mockImplementation(() =>
    Promise.resolve({
      url: "https://r2.example.com/logos/test.jpg",
      key: `logos/test-${Date.now()}.jpg`, // unique key each time
    })
  ),
  deleteFromR2: jest.fn().mockResolvedValue(undefined),
}));

afterEach(async () => {
  await prisma.media.deleteMany();
  await prisma.sellerProfile.deleteMany();
  await prisma.session.deleteMany();
  await prisma.user.deleteMany();
});

// helper
const createUser = async (overrides = {}) => {
  const result = await register({
    name: "John Doe",
    email: "john@test.com",
    password: "password123",
    role: "BUYER",
    ...overrides,
  });
  return result.user;
};

const mockLogoFile = {
  buffer: Buffer.from("fake image"),
  mimetype: "image/jpeg",
  originalname: "logo.jpg",
  size: 1024,
} as Express.Multer.File;

// ─── createSellerProfile ──────────────────────────────────────────────────────
describe("createSellerProfile", () => {
  it("should create seller profile and change role to SELLER", async () => {
    const user = await createUser();
    const profile = await createSellerProfile(user.id, { storeName: "Test Store" });

    expect(profile.storeName).toBe("Test Store");
    expect(profile.userId).toBe(user.id);

    const updated = await prisma.user.findUnique({ where: { id: user.id } });
    expect(updated?.role).toBe("SELLER");
  });

  it("should upload logo and save to Media table", async () => {
    const user = await createUser();
    const profile = await createSellerProfile(
      user.id,
      { storeName: "Test Store" },
      mockLogoFile
    );

    expect(profile.logoUrl).toBe("https://r2.example.com/logos/test.jpg");

    const media = await prisma.media.findFirst({ where: { uploaderId: user.id } });
    expect(media).not.toBeNull();
    expect(media?.key).toContain("logos/test-"); // unique key generated by mock
  });

  it("should throw 409 if seller profile already exists", async () => {
    const user = await createUser();
    await createSellerProfile(user.id, { storeName: "Test Store" });

    await expect(
      createSellerProfile(user.id, { storeName: "Another Store" })
    ).rejects.toThrow("Seller profile already exists");
  });
});

// ─── getMySellerProfile ───────────────────────────────────────────────────────
describe("getMySellerProfile", () => {
  it("should return seller profile with user and product count", async () => {
    const user = await createUser();
    await createSellerProfile(user.id, { storeName: "Test Store" });

    const profile = await getMySellerProfile(user.id);
    expect(profile.storeName).toBe("Test Store");
    expect(profile.user.email).toBe("john@test.com");
    expect(profile._count.products).toBe(0);
  });

  it("should throw 404 if seller profile not found", async () => {
    const user = await createUser();
    await expect(getMySellerProfile(user.id)).rejects.toThrow("Seller profile not found");
  });
});

// ─── updateSellerProfile ──────────────────────────────────────────────────────
describe("updateSellerProfile", () => {
  it("should update store name and description", async () => {
    const user = await createUser();
    await createSellerProfile(user.id, { storeName: "Test Store" });

    const updated = await updateSellerProfile(user.id, {
      storeName: "Updated Store",
      description: "Best store ever",
    });

    expect(updated.storeName).toBe("Updated Store");
    expect(updated.description).toBe("Best store ever");
  });

  it("should update logo and delete old one", async () => {
    const { deleteFromR2 } = require("../../src/utils/upload");
    const user = await createUser();
    await createSellerProfile(user.id, { storeName: "Test Store" }, mockLogoFile);

    await updateSellerProfile(user.id, {}, mockLogoFile);

    expect(deleteFromR2).toHaveBeenCalled();
  });

  it("should throw 404 if seller profile not found", async () => {
    const user = await createUser();
    await expect(
      updateSellerProfile(user.id, { storeName: "Updated Store" })
    ).rejects.toThrow("Seller profile not found");
  });
});

// ─── getPublicSellerProfile ───────────────────────────────────────────────────
describe("getPublicSellerProfile", () => {
  it("should return public seller profile", async () => {
    const user = await createUser();
    const profile = await createSellerProfile(user.id, { storeName: "Test Store" });

    const publicProfile = await getPublicSellerProfile(profile.id);
    expect(publicProfile.storeName).toBe("Test Store");
    expect(publicProfile._count.products).toBe(0);
  });

  it("should throw 404 if seller not found", async () => {
    await expect(getPublicSellerProfile("non-existent-id")).rejects.toThrow("Seller not found");
  });
});